version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./sounds:/app/sounds
      - django_static:/app/django_static
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
      - ./sounds:/app/sounds
      - django_static:/app/backend/django_static
    expose:
      - 8000
    env_file:
      - ./docker/.env.dev
volumes:
  django_static:
